### ISSUE TITLE
tag releases?

### ISSUE THREAD

**Issue by tayloraswift** [hummingbird-project/hummingbird-docs#18]
it is currently not possible to build documentation for this package [on Swiftinit](https://swiftinit.org/tags/hummingbird-docs) as it has no semver tags.

**Comment by adam-fowler** [comment]
Out of interest how is swiftinit running the dock build at the moment. I have a custom script which drags all the hummingbird package into this one package, copy the relevant symbol graph files into a separate folder and then build the docs from that. This allows me to get links between packages.

Not sure where the docc project is when it comes to generating documentation for multiple related packages

**Comment by tayloraswift** [comment]
Swiftinit doesn’t do anything special for the Hummingbird repos, it just builds docs for each package individually and links them against the other packages in the database.

Swiftinit does not compile the docs with DocC, it uses a different tool called [Unidoc](https://github.com/tayloraswift/swift-unidoc).

**Comment by adam-fowler** [comment]
I've tagged the last 1.x release 1.12.0 and I've tagged the 2.0 beta. I've kept the tags inline with the hummingbird repo, even though documentation for all the projects is contained here.

Hopefully one day I'll be able to move the docs into their actual packages and docc will be a build me a cross package set of documentation. Haven't investigated this much further recently
