### ISSUE TITLE
Todo Backend Tutorial missing `import Logging` in Section 2:Extending your Application

### ISSUE THREAD

**Issue by brucemontegani** [hummingbird-project/hummingbird-docs#21]
In the TodoBackend tutorial , Section 2: Extending your Application the `import Logging' is missing from the source in step 2 - Adding logging middleware and a Logger...

**Comment by adam-fowler** [comment]
Thanks. The tutorial has gone through a number of changes. I'm not surprised there's errors in it. I'll fix that up.
