### ISSUE TITLE
@Sendable compile error in Todos Tutorial at 'Add Your Application API' step 15 

### ISSUE THREAD

**Issue by globalflea** [hummingbird-project/hummingbird-docs#58]
i am new to both xcode & swift and was trying out hummingbird v2

I was trying out the tutorial (step by step) on Xcode 16 and Swift 6.0.
When i hit the step 'Add Your Application API' (step 15) where the endpoint `get()` was added the compiler complained with the following error: 

```
Instance method of non-Sendable type 'TodoController<Repository>' cannot be marked as '@Sendable'
```

i **guess** its because the compiler is unable to ascertain the generic param `struct TodoController<Repository: TodoRepository>` is indeed `@Sendable`.  It can't infer that `TodoController` is a `Sendable` since there is nothing to indicate that `TodoRepository` is also `Sendable`.

The problem went away (after googling for the reason) after i changed the generic param to read 
`struct TodoController<Repository: TodoRepository & Sendable>`

You may want to consider whether there's a need to add the `Sendable` in the tutorial code.

Interestingly, if i downloaded the final set of codes for the tutorial, i do not get the above errors. It happened only when i went through the tutorial following the steps provided

**Comment by adam-fowler** [comment]
Last time I compiled that was probably before Swift 6. Damn. I would be happy to accept a PR

**Comment by adam-fowler** [comment]
```swift
protocol TodosRepository: Sendable {
...
```
Would need to be in both docs and examples repositories. 

I'm away so can't easily add.

**Comment by adam-fowler** [comment]
I fixed this in the example code. It'll have to wait until I get back to fix the docs though.

**Comment by thoven87** [comment]
I opened a PR for this issue [here](https://github.com/hummingbird-project/hummingbird-docs/pull/61)

**Comment by adam-fowler** [comment]
PR has been merged and docs should update in next few minutes.
